Accounting/Models/ExchangeRate.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace Accounting.Models
{
    public class ExchangeRate
    {
        public int Id { get; set; }
        public int CurrencyId { get; set; }
        [DisplayFormat(DataFormatString = "{0:00.000000}")]
        public decimal Rate { get; set; }
        public DateTime Date { get; set; }

        public string CurrencyName
        {
            get
            {
                using (var c = new AccountingContext())
                {
                    return c.Currencies.Where(x => x.Id == CurrencyId).First().Name;
                }
            }
        }
    }
}

Accounting/Controllers/ExchangeRatesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Accounting.Models;

namespace Accounting.Controllers
{
    public class ExchangeRatesController : Controller
    {
        private AccountingContext db = new AccountingContext();

        public ActionResult Index()
        {
            if (MvcApplication.IsAuthorized())
            {
                var list = db.Currencies.ToList();
                list.Insert(0, new Currency() { Name = "Всі валюти", Id = -5 });
                ViewBag.Currencies = list;
                return View(db.ExchangeRates.ToList());
            }
            else return RedirectToAction("Index", "Auth");
        }
        [HttpPost]
        public ActionResult Index(int currencyId)
        {
            var list = db.Currencies.ToList();
            list.Insert(0, new Currency() { Name = "Всі валюти", Id = -5 });
            ViewBag.Currencies = list;
            if (currencyId != -5)
            {
                return View(db.ExchangeRates.ToList().Where(x => x.CurrencyId == currencyId));
            }
            else return View(db.ExchangeRates);
        }

        public ActionResult Create()
        {
            ViewBag.Currencies = db.Currencies.ToList();
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CurrencyId,Rate,Date")] ExchangeRate exchangeRate)
        {
            if (ModelState.IsValid)
            {
                db.ExchangeRates.Add(exchangeRate);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Currencies = db.Currencies.ToList();

            return View(exchangeRate);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExchangeRate exchangeRate = db.ExchangeRates.Find(id);
            if (exchangeRate == null)
            {
                return HttpNotFound();
            }
            ViewBag.Currencies = db.Currencies.ToList();
            return View(exchangeRate);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CurrencyId,Rate,Date")] ExchangeRate exchangeRate)
        {
            if (ModelState.IsValid)
            {
                db.Entry(exchangeRate).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Currencies = db.Currencies.ToList();

            return View(exchangeRate);
        }

        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Accounting/Controllers/NBUImportController.cs
using Accounting.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Xml;

namespace Accounting.Controllers
{
    public class NBUImportController : Controller
    {
        AccountingContext context = new AccountingContext();
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> Import(string firstDate, string secondDate)
        {
            foreach (var item in context.Currencies)
            {
                foreach (var date in DateRange(DateTime.Parse(firstDate), DateTime.Parse(secondDate)))
                {
                    try
                    {
                        HttpClient client = new HttpClient();

                        string uri = String.Format("https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange?valcode={0}&date={1}", item.Name, date.ToString("yyyyMMdd"));

                        string response = await client.GetStringAsync(uri);

                        XmlDocument doc = new XmlDocument();
                        doc.LoadXml(response);
                        XmlElement root = doc.DocumentElement;

                        string rate = root.FirstChild["rate"].InnerText;
                        var numberFormatInfo = new NumberFormatInfo { NumberDecimalSeparator = "." };
                        decimal d = decimal.Parse(rate, numberFormatInfo);

                        context.ExchangeRates.Add(new ExchangeRate() { CurrencyId = item.Id, Date = date, Rate = d });
                    }
                    catch
                    {

                    }
                   
                }
            }
            await context.SaveChangesAsync();

            return RedirectToAction("Index", "ExchangeRates");
        }

        protected override void Dispose(bool disposing)
        {
            context.Dispose();
            base.Dispose(disposing);
        }
        private IEnumerable<DateTime> DateRange(DateTime fromDate, DateTime toDate)
        {
            return Enumerable.Range(0, toDate.Subtract(fromDate).Days + 1)
                             .Select(d => fromDate.AddDays(d));
        }
    }
}

Accounting/Views/ExchangeRates/Create.cshtml
@model Accounting.Models.ExchangeRate

@{
    ViewBag.Title = "Додати курс валют";
}

<h2>Додати курс валют</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Курси валют</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Валюта</label>

            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CurrencyId, new SelectList(ViewBag.Currencies, "Id", "Name"), new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Курс</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Дата</label>
            <div class="col-md-10">
                <input type="date" name="Date" class="form-control"  />

                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Додати" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Повернутися до списку", "Index")
</div>

Accounting/Views/ExchangeRates/Edit.cshtml
@model Accounting.Models.ExchangeRate

@{
    ViewBag.Title = "Редагувати";
}

<h2>Редагувати</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Курси валют</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        <label class="control-label col-md-2">Валюта</label>

        <div class="col-md-10">
            @Html.DropDownListFor(model => model.CurrencyId, new SelectList(ViewBag.Currencies, "Id", "Name"),  new {  @class = "form-control" } )
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Курс</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Rate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Rate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Дата</label>
        <div class="col-md-10">
            <input type="date" value=@Model.Date.ToString("yyyy-MM-dd") name="Date" class="form-control" />
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Зберегти" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Повернутися до списку", "Index")
</div>

Accounting/Views/ExchangeRates/Index.cshtml
@model IEnumerable<Accounting.Models.ExchangeRate>

@{
    ViewBag.Title = "Курси валют";
}

<h2>Курси валют</h2>
@using (Html.BeginForm("Index", "ExchangeRates", FormMethod.Post))
{



    <div class="form-group">

        <label class="control-label col-md-2">Виберіть валюту:</label>
        @Html.DropDownList("currencyId", new SelectList(ViewBag.Currencies, "Id", "Name"), new { @class = "form-control " })
        <input type="submit" value="Вибрати" class="btn btn-default" />
    </div>


}
<p>
    @Html.ActionLink("Додати новий", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Валюта
        </th>
        <th>
            Курс
        </th>
        <th>
            Дата
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CurrencyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rate)
            </td>
            <td>
                @item.Date.ToShortDateString()
            </td>
            <td>
                @Html.ActionLink("Редагувати", "Edit", new { id = item.Id })
            </td>
        </tr>
    }

</table>
@using (Html.BeginForm("Index", "NBUImport", FormMethod.Get))
{
    <div class="form-group">
   
            <input type="submit" value="Імпорт курсів з НБУ" class="btn btn-default" />
       
    </div>
}